---
apiVersion: v1
kind: Secret
metadata:
  name: gui-db-credentials
type: Opaque
data:
  user: YWRtaW4K
  password: cGxlYXNlY2hhbmdlbWU=
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gui-config
data:
  config.json: |
    {  
      "petServiceUrl": "http://k8s.mytanzu.xyz/pets",
      "stage": "DEV",
      "debug": "False",
      "stage_color": "blue"
    }
---
kind: Deployment
apiVersion: apps/v1
metadata:  
  name: gui-app
  labels:
    app: gui-app
    group: micro-pet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gui-app
      group: micro-pet
  template:
    metadata:
      labels:
        app: gui-app
        group: micro-pet
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: gui-config
            items:
            - key: config.json
              path: config.json
      containers:
        - name: gui
          image: localregistry:5000/micropet/gui:dev
          imagePullPolicy: Always
          ports:
            - name: gui
              containerPort: 80
          volumeMounts:
            - name: config-volume
              mountPath: /usr/share/nginx/html/gui/assets/config                            
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: gui-service
  labels:
    app: gui-app
    group: micro-pet
spec:
  ports:
    - protocol: TCP
      name: gui
      port: 80
  selector:
    app: gui-app
    group: micro-pet
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: gui-ingress
spec:
  rules:
  - host: k8s.mytanzu.xyz
    http:
      paths:
      - path: /gui
        pathType: Prefix
        backend:
          service:
            name: gui-service
            port:
              number: 80

              


