apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: gui-angular-js
  labels:
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/has-tests: "true"
    app.kubernetes.io/part-of: micropets
    app.kubernetes.io/name: gui
    apis.apps.tanzu.vmware.com/register-api: "false"
  annotations:
    autoscaling.knative.dev/minScale: "1"
spec:
  build:
    env:
      - name: BP_NODE_VERSION
        value: "v18.14.1"
      - name: BP_LOG_LEVEL
        value: "DEBUG"
  source:
    git:
      url: https://github.com/bmoussaud/micropets-gui-angular-js/
      ref:
        branch: main
  serviceClaims:
    - name: app-config
      ref:
        apiVersion: v1
        kind: Secret
        name: gui-config
  env:
    - name: SERVICE_BINDING_ROOT
      value: "/workspace/dist/assets"
    - name: PETS_SERVICE
      value: http://pets-golang.micropets-int/pets
  params:
    - name: testing_pipeline_matching_labels
      value:
        apps.tanzu.vmware.com/pipeline: skip-test
    - name: scanning_source_policy
      value: scan-policy-angular
    - name: scanning_image_policy
      value: scan-policy-angular
    - name: userId
      value: 1001
    - name: gitops_commit_message
      value: gui dev supplychain@cluster.local
